sudo: false
language: python
python:
- '3.6.2'
branches:
  only:
  - master
install:
- pip install -r requirements.txt
deploy:
  provider: heroku
  api_key:
    secure: "7f6178ce-0f8f-4042-abb8-b75b304447fd"
  app: medicarewebsite
