# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 21:37
from __future__ import unicode_literals

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('deleted', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deletado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('remedio', models.CharField(max_length=150, verbose_name='Remédio')),
                ('quantity', models.IntegerField(null=True, verbose_name='Quantidade')),
                ('quantity_unit', models.CharField(blank=True, choices=[('mg', 'mg'), ('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('cx', 'cx')], max_length=2, null=True, verbose_name='Unidade')),
                ('pills', models.IntegerField(verbose_name='Quantidade (em pílulas)')),
                ('doctor', models.CharField(max_length=150, verbose_name='Nome do Médico')),
                ('crm', models.CharField(max_length=10, verbose_name='CRM do Médico')),
                ('prescription', models.FileField(upload_to=data.models.prescription_file_upload, verbose_name='Receita')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['remedio'],
            },
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['remedio'], 'verbose_name': 'Doação', 'verbose_name_plural': 'Doações'},
        ),
        migrations.AlterField(
            model_name='donation',
            name='quantity_unit',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Unidade'),
        ),
    ]
