# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20171007_1837'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reserve',
            new_name='Reservation',
        ),
    ]
