# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-26 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20171007_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('deleted', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deletado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('crm', models.CharField(max_length=10, verbose_name='CRM do Médico')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('state', models.CharField(max_length=2, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Donation_Itens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('deleted', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deletado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('pills', models.IntegerField(verbose_name='Quantidade (em pílulas)')),
            ],
            options={
                'verbose_name': 'Doação',
                'verbose_name_plural': 'Doações',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('deleted', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deletado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('active_principle', models.CharField(max_length=150, verbose_name='Principio Ativo')),
                ('remedio', models.CharField(max_length=150, verbose_name='Remédio')),
                ('tarja', models.CharField(max_length=20, null=True, verbose_name='Tarja')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['remedio'],
            },
        ),
        migrations.CreateModel(
            name='Medicine_Apresentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('deleted', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deletado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('ggrem', models.IntegerField(verbose_name='Regulação Econômica')),
                ('size', models.IntegerField(null=True, verbose_name='Tamanho')),
                ('size_unit', models.CharField(blank=True, choices=[('mg', 'mg'), ('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('cx', 'cx')], max_length=2, null=True, verbose_name='Unidade')),
                ('laboratory', models.CharField(max_length=30, verbose_name='Laboratório')),
                ('complement', models.TextField(blank=True, verbose_name='Complemento')),
                ('id_medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Medicine', verbose_name='Id Remédio')),
            ],
            options={
                'verbose_name': 'Apresentação',
                'verbose_name_plural': 'Apresentações',
                'ordering': ['id_medicine'],
            },
        ),
        migrations.CreateModel(
            name='Reservation_Itens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('deleted', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deletado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('pills', models.IntegerField(verbose_name='Quantidade (em pílulas)')),
                ('id_apresentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Medicine_Apresentation')),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Customer')),
                ('id_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Doctor')),
            ],
            options={
                'verbose_name': 'Itens de Reserva',
                'verbose_name_plural': 'Itens de Reservas',
                'ordering': ['id_reservation'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('deleted', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deletado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('manufacture_date', models.DateField(verbose_name='Data de Fabricação')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('stock_quantity', models.IntegerField(verbose_name='Quantidade em Estoque')),
                ('minimun_quantity', models.IntegerField(verbose_name='Quantidade Mínima')),
                ('id_donation_itens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Donation_Itens')),
                ('id_reservation_itens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Reservation_Itens')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={},
        ),
        migrations.RemoveField(
            model_name='donation',
            name='pills',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='quantity_unit',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='remedio',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='crm',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='pills',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='quantity_unit',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='remedio',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(null=True, verbose_name='Data de Vencimento do Remédio'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='date',
            field=models.DateField(verbose_name='Data de Vencimento do Remédio'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Nome Completo'),
        ),
        migrations.AddField(
            model_name='reservation_itens',
            name='id_reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Reservation'),
        ),
        migrations.AddField(
            model_name='donation_itens',
            name='id_apresentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Medicine_Apresentation'),
        ),
        migrations.AddField(
            model_name='donation_itens',
            name='id_donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Donation'),
        ),
        migrations.AddField(
            model_name='donation_itens',
            name='id_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Supplier'),
        ),
    ]
