# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-26 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20171026_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine_apresentation',
            options={'ordering': ['id_medicine'], 'verbose_name': 'Apresentação do Medicamento', 'verbose_name_plural': 'Apresentação dos Medicamentos'},
        ),
        migrations.AlterField(
            model_name='medicine',
            name='active_principle',
            field=models.CharField(max_length=150, verbose_name='Princípio Ativo'),
        ),
        migrations.AlterField(
            model_name='medicine_apresentation',
            name='ggrem',
            field=models.BigIntegerField(verbose_name='Regulação Econômica'),
        ),
        migrations.AlterField(
            model_name='medicine_apresentation',
            name='id_medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Medicine', verbose_name='Id Medicamento'),
        ),
    ]
