# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-26 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20171026_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine_apresentation',
            name='ggrem',
            field=models.CharField(max_length=15, verbose_name='Código Regulação Econômica'),
        ),
    ]
