# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-26 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20171026_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='doctor',
            name='situation',
            field=models.CharField(default='Atualizar', max_length=50, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='medicine_apresentation',
            name='ggrem',
            field=models.CharField(default='Atualizar', max_length=15, verbose_name='Código Regulação Econômica'),
        ),
        migrations.AlterField(
            model_name='medicine_apresentation',
            name='laboratory',
            field=models.CharField(max_length=200, verbose_name='Laboratório'),
        ),
    ]
