# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-26 20:30
from __future__ import unicode_literals

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20171026_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='situation',
        ),
        migrations.AlterField(
            model_name='medicine_apresentation',
            name='ggrem',
            field=models.CharField(max_length=15, verbose_name='Código Regulação Econômica'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(verbose_name='Data de Vencimento do Remédio'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='prescription',
            field=models.FileField(upload_to=data.models.prescription_file_upload, verbose_name='Prescrição Médica'),
        ),
    ]
