# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-27 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20171026_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Itens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('deleted', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deletado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('manufacture_date', models.DateField(null=True, verbose_name='Data de Fabricação')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('id_medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Medicine')),
            ],
            options={
                'verbose_name': 'Itens de Estoque',
                'verbose_name_plural': 'Itens de Estoque',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['id'], 'verbose_name': 'Doação', 'verbose_name_plural': 'Doações'},
        ),
        migrations.AlterModelOptions(
            name='donation_itens',
            options={'ordering': ['id'], 'verbose_name': 'Itens de Doação', 'verbose_name_plural': 'Itens de Doações'},
        ),
        migrations.AlterModelOptions(
            name='medicine_apresentation',
            options={'ordering': ['id_medicine'], 'verbose_name': 'Apresentação de Medicamento', 'verbose_name_plural': 'Apresentação de Medicamentos'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['id'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['id'], 'verbose_name': 'Estoque', 'verbose_name_plural': 'Estoque'},
        ),
        migrations.RemoveField(
            model_name='stock',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='manufacture_date',
        ),
        migrations.AddField(
            model_name='stock_itens',
            name='id_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Stock'),
        ),
    ]
