# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-27 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20171027_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.TextField(default='Atualizar', verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.TextField(default='Atualizar', verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Completo'),
        ),
    ]
