# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-27 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20171027_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_itens',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='id_donation_itens',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Donation_Itens'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='id_reservation_itens',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Reservation_Itens'),
        ),
    ]
